version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            pip install --upgrade pip setuptools wheel
            pip install -e .[develop]
      - save_cache:
          key: v1-dependencies-{{ checksum "setup.py" }}
          paths:
            - ./venv
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pyenv install --skip-existing 3.5.5 3.6.5 3.7-dev
            pyenv local 3.5.5 3.6.5 3.7-dev
            detox
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = $PYPI_REPOSITORY" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create Packages
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
  test_and_deploy_testing:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+.\d+.\d+rc\d*$/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+.\d+.\d+rc\d*$/
            branches:
              ignore: /.*/
          context: testing
  test_and_deploy_production:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+.\d+.\d+$/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          context: production
